GNOMAD_V3_GENOMES:
  chroms:
    #- "chr22"
    #- "chr21"
    - "all"
  scenarios:
    all_nfe:
      props: "1.0, 0.0, 0.0, 0.0, 0.0" # proportion across populations
      n: 10000 # number of samples
    uniform_eurasia:
      props: "0.25, 0.25, 0.25, 0.25, 0.0"
      n: 10000

UKBB_EXOMES:
    chroms:
        - "all"
    scenarios:
        barts:
            props: "1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        birmingham:
            props: "0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        bristol:
            props: "0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        bury:
            props: "0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        cardiff:
            props: "0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        croydon:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        edinburgh:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        glasgow:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        hounslow:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        leeds:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        liverpool:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 30000
        manchester:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        middlesborough:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        newcastle:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        nottingham:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        oxford:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        reading:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
        sheffield:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0"
            n: 10000
            #stockport:
            #    props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0"
            #    n: 10000
        stoke:
            props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0"
            n: 10000
            #swansea:
            #    props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0"
            #    n: 5000
            #wrexham:
            #    props: "0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0"
            #    n: 5000
        uniform:
            props: "0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545, 0.04545"
            n: 10000

UKBB_EXOMES_PCA:
    chroms:
        - "all"
    scenarios:
        group_01_sd:
            props: "1.0, 0.0, 0.0"
            n: 4000
        group_02_sd:
            props: "0.0, 1.0, 0.0"
            n: 4000
        group_10_sd:
            props: "0.0, 0.0, 1.0"
            n: 4000
        narrow:
            props: "1.0, 0.0"
            n: 9600
        broad:
            props: "0.0, 1.0"
            n: 9600
        #group_0.5_sd:
        #    props: "1.0, 0.0, 0.0, 0.0, 0.0"
        #    n: 10000
        #group_1_sd:
        #    props: "0.0, 1.0, 0.0, 0.0, 0.0"
        #    n: 10000
        #group_2_sd:
        #    props: "0.0, 0.0, 1.0, 0.0, 0.0"
        #    n: 10000
        #group_5_sd:
        #    props: "0.0, 0.0, 0.0, 1.0, 0.0"
        #    n: 10000
        #group_10_sd:
        #    props: "0.0, 0.0, 0.0, 0.0, 1.0"
        #    n: 10000
